import { useAppTranslation } from '~/hooks'

//const { t } = useAppTranslation()
export const layoutMenu = [{
  "Key": "/category-management",
  "Id": 1001,
  "Text": "Quản lý danh mục",
  "Icon": "OrderedListOutlined",
  "Data": {
    "Id": 1001,
    "Code": "1001",
    "Name": "Quản lý danh mục",
    "NameEn": "Category",
    "Url": "",
    "IsDeleted": "N",
    "CreatedBy": "admin",
    "CreatedDate": "2022-06-23T21:54:14",
    "ModifiedBy": "admin",
    "ModifiedDate": "2022-10-11T15:17:44",
    "OrderNumber": 1,
    "Status": "A",
    "Layout": "DefaultLayout",
    "IsPrivate": true,
    "ShowOnMenu": true,
    "MenuPosition": true
  },
  "Children": [],
  "Label": "quản lý danh mục",
  "Code": "1001"
},
{
  "Key": "/categorycrawl",
  "Id": 1001,
  "Text": "Config crawl",
  "Icon": "CodeOutlined",
  "Data": {
    "Id": 1001,
    "Code": "1001",
    "Name": "Cấu hình crawl",
    "NameEn": "Config crawl",
    "Url": "",
    "IsDeleted": "N",
    "CreatedBy": "admin",
    "CreatedDate": "2022-06-23T21:54:14",
    "ModifiedBy": "admin",
    "ModifiedDate": "2022-10-11T15:17:44",
    "OrderNumber": 1,
    "Status": "A",
    "Layout": "DefaultLayout",
    "IsPrivate": true,
    "ShowOnMenu": true,
    "MenuPosition": true
  },
  "Children": [],
  "Label": "quản lý danh mục",
  "Code": "1001"
},
{
  "Id": 1002,
  "Text": "Quản lý bài viết",
  "Icon": "FundViewOutlined",
  "Data": {
    "Id": 1002,
    "Code": "1002",
    "Name": "Quản lý bài viết",
    "NameEn": "Post management",
    "IsDeleted": "N",
    "CreatedBy": "admin",
    "CreatedDate": "2022-06-23T21:54:14",
    "ModifiedBy": "admin",
    "ModifiedDate": "2022-08-31T16:17:02",
    "OrderNumber": 2,
    "Status": "A",
    "Layout": "DefaultLayout",
    "IsPrivate": true,
    "ShowOnMenu": true,
    "MenuPosition": false
  },
  "Children": [
    {
      "Key": "/creativepostcrawl",
      "Id": 1003,
      "ParentId": 1002,
      "Text": "Bài viết Crawl",
      "Icon": "DownloadOutlined",
      "Data": {
        "Id": 1003,
        "ParentId": 1002,
        "Code": "1003",
        "Name": "Bài viết Crawl",
        "NameEn": "Post Crawl",
        "Url": "/creativepostcrawl",
        "IsDeleted": "N",
        "CreatedBy": "admin",
        "CreatedDate": "2022-06-23T21:54:14",
        "ModifiedBy": "admin",
        "ModifiedDate": "2022-10-11T15:18:28",
        "OrderNumber": 3,
        "Status": "A",
        "Layout": "DefaultLayout",
        "IsPrivate": true,
        "ShowOnMenu": true,
        "MenuPosition": true
      },
      "Children": [],
      "Label": "Bài viết Crawl",
      "Code": "1003"
    },
    {
      "Key": "/creativepost",
      "Id": 1004,
      "ParentId": 1002,
      "Text": "Bài viết biên tập",
      "Icon": "UploadOutlined",
      "Data": {
        "Id": 1004,
        "ParentId": 1002,
        "Code": "1004",
        "Name": "Bài viết biên tập",
        "NameEn": "Post editor",
        "Url": "/creativepost",
        "IsDeleted": "N",
        "CreatedBy": "admin",
        "CreatedDate": "2022-06-23T21:54:14",
        "ModifiedBy": "admin",
        "ModifiedDate": "2022-10-11T15:19:20",
        "OrderNumber": 4,
        "Status": "A",
        "Layout": "DefaultLayout",
        "IsPrivate": true,
        "ShowOnMenu": true,
        "MenuPosition": true
      },
      "Children": [],
      "Label": "Bài viết biên tập",
      "Code": "1004"
    },
  ],
  "Label": "Quản lý bài viết",
  "Code": "1002"
},
{
  "Key": "/administrator",
  "Id": 1003,
  "Text": "Quản trị viên",
  "Icon": "UsergroupAddOutlined",
  "Label": "Quản trị viên",
  "Data": {
    "Id": 1003,
    "Code": "1003",
    "Name": "Quản trị viên",
    "NameEn": "Administrator",
    "Url": "",
    "IsDeleted": "N",
    "CreatedBy": "admin",
    "CreatedDate": "2022-06-23T21:54:14",
    "ModifiedBy": "admin",
    "ModifiedDate": "2022-10-11T15:17:44",
    "OrderNumber": 1,
    "Status": "A",
    "Layout": "DefaultLayout",
    "IsPrivate": true,
    "ShowOnMenu": true,
    "MenuPosition": true
  },
  "Children": [
    {
      "Key": "/administrator/users-management",
      "Id": 1004,
      "ParentId": 1003,
      "Text": "Quản lý tài khoản",
      "Icon": "UserOutlined",
      "Label": "Quản lý tài khoản",
      "Data": {
        "Id": 1004,
        "ParentId": 1003,
        "Code": "1004",
        "Name": "Quản lý tài khoản",
        "NameEn": "User",
        "Url": "/users-management",
        "IsDeleted": "N",
        "CreatedBy": "admin",
        "CreatedDate": "2022-06-23T21:54:14",
        "ModifiedBy": "admin",
        "ModifiedDate": "2022-10-11T15:18:28",
        "OrderNumber": 3,
        "Status": "A",
        "Layout": "DefaultLayout",
        "IsPrivate": true,
        "ShowOnMenu": true,
        "MenuPosition": true
      },
      "Children": [],
    }
  ],
},

]