export const storageKeys = {
  TOKEN: 'TOKEN',
  CURRENT_USER: 'CURRENT_USER',
  PAGE_SETTINGS: 'PAGE_SETTINGS',
  EXPANED_ORG: 'EXPANED_ORG',
  CURRENT_PAGE: 'CURRENT_PAGE',
  CURRENT_PAGE_INFO: 'CURRENT_PAGE_INFO',
  LANGUAGE: 'LANGUAGE',
}
